# Site
name: "Benjamin Masters"
title: "bpmasters.me"
description: "I am a PhD student in biomedical engineering at the University of Waterloo where I primarily study the perception and measurement of effort in conversation. I work in the Hearing Lab under the supervision of Ewen MacDonald, and am jointly working on collaborative research projects with Oticon's Eriksholm Research Centre. I also hold a Masters of Applied Science in systems design engineering from Waterloo, and a Bachelor of Science in acoustical engineering from Purdue University."
photo_url: 'assets/images/avatar.jpeg'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
google_analytics: 'G-JSXGPYZBMQ'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ben:
    name: Ben Masters
    display_name: Ben
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    avatar: 'assets/images/avatar.jpeg'
    email: bpmasters@mac.com
    web: 
    twitter: 
    description: "Hearing Researcher and Acoustic Engineer"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
