title: Benjamin Masters # your name (or website title) here
description:
  Acoustical Engineer
logo: "/images/Logo.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have an interest and passion for the overlap between the fields of engineering acoustics and hearing science.
  <br><br>
  Some examples of my work in these areas can be seen on this page.
  <br><br>
  Master of Applied Science<br>Systems Design Engineering<br>University of Waterloo, Expected '24
  <br><br>
  Bachelor of Science in Engineering<br>Acoustical Engineering<br>Purdue University, May '22
  <br><br>
  Contact me:
  Bpmasters@mac.com
  <br><br>
  <a href="https://www.linkedin.com/in/benjamin-p-masters/">View My LinkedIn Profile</a>
  <br>
  <a href="/pdf/Resume.pdf">View My Resume</a>



theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
